### ISSUE TITLE
Print Error Checks 

### ISSUE THREAD

**Issue by EmFresh** [Promethaes/Tone-Fire#2]
I suggest printing the error checks before exiting each function. I've made a function to handle that before so if you want I can sauce you the code.

**Comment by Promethaes** [comment]
if im interpreting this correctly, then there is already an error printing function for FMOD core api and studio api

**Comment by EmFresh** [comment]
I'm not sure how I missed that you were using the errorcheck function lol, my bad. with that said I was looking at _isChannelPlaying and saw that one would only print something if there's nothing wrong.
